### ISSUE TITLE
Decide on a cloud service to host your servers

### ISSUE THREAD

**Issue by haocencol** [vineesh92/Team-5-Comp-313-001-#2]

**Comment by haocencol** [comment]
@vineesh92 is your team done with this?  If yes, attach a file explaining how you arrived at this decision.

**Comment by jithinjoshy121** [comment]
GoDaddy or Google Firebase are the cloud services we consider to host our servers.

**Comment by ManasaMohanan** [comment]
In the initial phase of project , we decided to use  Google Firebase as the back-end. But in the later phase,we realized that the size of the data is more than we expected. So it will be very difficult to manage the data in google Firebase, since we need to enter the data manually in Json format. So we decided to use PHP with MySQL as the back-end.

**Comment by haocencol** [comment]
I presume you are finished with this issue.  Please close it.
